name: Automated API tests using Newman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Run API tests
        run: |
          newman run "38474672-daf400b7-e878-406f-9814-6e1ddffeda2d" -e "38474672-1bab6b0e-f410-4fd9-8855-6b60fdc61c3c" -d"csvData.csv"
